# HTTPS setup
server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: conf/certificates/server.p12
      keyStoreType: PKCS12
      keyStorePassword: password
      trustStorePath: conf/certificates/truststore.jks
      trustStorePassword: password
      needClientAuth: true
      wantClientAuth: true
logging:
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
    - type: logstash-socket
      host: ${logstash_server}
      port: ${logstash_udp_port}
      includeContext: true

